title: Your Blog Title
email: youremail@domain.com
description: >- # this means to ignore newlines until "baseurl:"
  Blog description
baseurl: ""
url: "https://yoursite.github.io"
permalink: pretty
logo: "/assets/img/logo.svg"
phone: +1234
location: "123 Street. Nowhere, Earth"

header_pages:
  - index.html
  - about.md
  - portfolio.md

words_per_minute: 200

# Default post thumbnail path
posthumbnail: images/any.jpg

show_excerpts: true

# Amount of post to show on home page
paginate: 5

disqus:
  shortname: ""

mailchimp-list: //redgadgets.us10.list-manage.com/subscribe/post?u=210acce5db69d3d4a04b0e25d&amp;id=18c6708f40"

facebook:
  app_id: 1234
  publisher: 1234
  admins: 1234

google_analytics: UA-000000000-16

webmaster_verifications:
  google: 1234
  bing: 1234
  alexa: 1234
  yandex: 1234
  baidu: 1234

social:
  name: Your Name
  links:
    - https://twitter.com/YourInfo
    - https://www.facebook.com/YourInfo
    - https://www.linkedin.com/in/YourInfo
    - https://plus.google.com/+YourInfo
    - https://github.com/YourInfo
    - https://keybase.io/YourInfo

google_analytics: UA-000000000-16

webmaster_verifications:
  google: 1234
  bing: 1234
  alexa: 1234
  yandex: 1234
  baidu: 1234

author: Your Name

twitter:
  username: YourInfo
  card: summary

twitter_username: YourInfo
github_username:  YourInfo
dribbble_username:
facebook_username:
flickr_username:
instagram_username:
linkedin_username:
pinterest_username:
youtube_username:

rss: true


# Build settings
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
